apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bigtableautoscalers.storage.spotify.com
spec:
#  additionalPrinterColumns:
#  - JSONPath: .status.ready
#    description: BigtableAutoscaler Status
#    name: Ready
#    type: string
  group: storage.spotify.com
  names:
    kind: BigtableAutoscaler
    listKind: BigtableAutoscalerList
    plural: bigtableautoscalers
    singular: bigtableautoscaler
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: This is the Schema for the BigtableAutoscaler API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification defines the desired state of BigtableAutoscaler
          type: object
          properties:
            instanceId:
              description: Bigtable InstanceId.
              type: string
            cluster:
              description: List of Bigtable Autoscale configurations for clusters
              type: array
              items:
                type: object
                properties:
                  clusterId:
                    type: string
                  minNodes:
                    type: integer
                  maxNodes:
                    type: integer
                  cpuTarget:
                    type: number
                required:
                - clusterId
                - minNodes
                - maxNodes
                - cpuTarget
        status:
          description: Status of the API
          properties:
            ready:
              description: ready or not ?
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
